name: E2E Tests

on:
  pull_request:
    branches: [trunk]

jobs:
  test:
    name: Playwright e2e Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          composer install --prefer-dist --no-progress

      - name: Npm build
        run: npm run build

      - name: Install wp-env
        run: npm install -g @wordpress/env

      - name: Start wp-env
        run: wp-env start

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Stop wp-env
        if: always()
        run: wp-env stop
